//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio_Table
    {
        public int portfolioID { get; set; }
        public string stock1_name { get; set; }
        public string stock1_tkr { get; set; }
        public decimal stock1_beg_investment_value { get; set; }
        public decimal stock1_beg_share_price { get; set; }
        public Nullable<int> stock1_no_shares { get; set; }
        public decimal stock1_closing_share_price { get; set; }
        public decimal stock1_ending_investment_value { get; set; }
        public string stock2_name { get; set; }
        public string stock2_tkr { get; set; }
        public decimal stock2_beg_investment_value { get; set; }
        public decimal stock2_beg_share_price { get; set; }
        public Nullable<int> stock2_no_shares { get; set; }
        public decimal stock2_closing_share_price { get; set; }
        public decimal stock2_ending_investment_value { get; set; }
        public string stock3_name { get; set; }
        public string stock3_tkr { get; set; }
        public decimal stock3_beg_investment_value { get; set; }
        public decimal stock3_beg_share_price { get; set; }
        public Nullable<int> stock3_no_shares { get; set; }
        public decimal stock3_closing_share_price { get; set; }
        public decimal stock3_ending_investment_value { get; set; }
    }
}
