//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTkr
    {
        public string Symbol { get; set; }
        public string Name { get; set; }
        public string IPOyear { get; set; }
        public string Industry { get; set; }
    }
}
